from random import randint
from turtle import Turtle
buddy = Turtle()
buddy.color('green')
buddy.shape('turtle')
buddy.penup()
buddy.goto(-160, 100)
buddy.pendown()
udacity = Turtle()
udacity.color('blue')
udacity.shape('turtle')
udacity.penup()
udacity.goto(-160, 70)
udacity.pendown()
documentary = Turtle()
documentary.color('red')
documentary.shape('turtle')
documentary.penup()
documentary.goto(-160, 40)
documentary.pendown()
forex = Turtle()
forex.color('orange')
forex.shape('turtle')
forex.penup()
forex.goto(-160, 10)
forex.pendown()
for movement in range(100):
    buddy.forward(randint(1,5))
    udacity.forward(randint(1,5))
    documentary.forward(randint(1,5))
    forex.forward(randint(1,5))
